name: Security audit

on:
  push:
  workflow_dispatch:
    inputs:
      tags:
        required: false
        description: 'Security audit'

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_AGRIAN_REGISTRY_INDEX: ${{ secrets.AGRIAN_CRATES_REGISTRY }}

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@ee29fafb6aa450493bac9136b346e51ea60a8b5e
        with:
          ssh-private-key: |
            ${{ secrets.MAC_OS_BUILD_AGENT_PRIVATE_KEY }}
      - uses: actions/checkout@v2
      - name: Install cargo-audit
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
